image: gitpod/workspace-full

ports:
  - port: 8000
    onOpen: open-preview
    visibility: public
  - port: 5173
    onOpen: ignore
    visibility: public

tasks:
  - name: Setup PHP & Laravel
    init: |
      sudo apt-get update
      sudo apt-get install -y php8.2 php8.2-cli php8.2-mbstring php8.2-xml php8.2-bcmath php8.2-curl php8.2-zip php8.2-sqlite3 unzip
      curl -sS https://getcomposer.org/installer | php
      sudo mv composer.phar /usr/local/bin/composer
      composer install
      cp .env.example .env || true
      php artisan key:generate
      mkdir -p database && touch database/database.sqlite
      sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
      sed -i 's#^DB_DATABASE=.*#DB_DATABASE=database/database.sqlite#' .env
    command: |
      php artisan serve --host 0.0.0.0 --port 8000

  - name: Vite Dev
    command: |
      npm install
      npm run dev -- --host 0.0.0.0 --port 5173
